//MOVIES
export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_RECIEVE = "MOVIES_RECIEVE";

//SINGLE_MOVIE
export const SINGLE_MOVIE_REQUEST = "SINGLE_MOVIE_REQUEST";
export const SINGLE_MOVIE_RECIEVE = "SINGLE_MOVIE_RECIEVE";

//SEARCH
export const SEARCH_MOVIE_REQUEST = "SEARC_MOVIE_REQUEST";
export const SEARCH_MOVIE_RECIEVE = "SEARC_MOVIE_RECIEVE";
