//MOVIES
export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_RECIEVE = "MOVIES_RECIEVE";
//GENRES
export const GENRES_REQUEST = "GENRES_REQUEST";
export const GENRES_RECIEVE = "GENRES_RECIEVE";
//ADD NEW MOVIE
export const ADD_NEW_MOVIE_REQUEST = "ADD_NEW_MOVIE_REQUEST";
export const ADD_NEW_MOVIE_RECIEVE = "ADD_NEW_MOVIE_RECIEVE";
