//MOVIES
export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_RECIEVE = "MOVIES_RECIEVE";
//GENRES
export const GENRES_REQUEST = "GENRES_REQUEST";
export const GENRES_RECIEVE = "GENRES_RECIEVE";
//UPLOAD IMG
export const UPLOAD_IMG = "UPLOAD_IMG";
